#pragma once

enum Error
{
	ERROR_SUCCESS,					//0
	ERROR_LOADING_TEXTURE,			//1
	ERROR_LOADING_TEXT_FILE,		//2
	ERROR_GAME_LOADING_CURSOR,		//3
	ERROR_BUTTON_LOADING_TEXTURE,	//4
	ERROR_ENEMY_LOADING_TEXTURE,	//5
	ERROR_ENEMY_LOADING_FILE,		//6
	ERROR_LEVEL_LOADING_TEXTURE,	//7
	ERROR_LEVEL_LOADING_FILE,		//8
	ERROR_MENU_LOADING_TEXTURE,		//9
	ERROR_TRACK_LOADING_TEXTURE,	//10
	ERROR_TRACK_IS_CORRUPTED,		//11
	ERROR_TEST,						//12
};